language: python
before_install:
- pip install pycodestyle
install:
- pip install -r requirements.txt
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
- pytest --cov=artellapipe
- sphinx-apidoc -f -e -o docs/sphinx artellapipe
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: kDyYlspizGfvFEvYxvhp6nR7j39BH7BiG/STBwRFJYmt6uq9xXogj0o6k+GfFKfvruD6TKdWCwQpxbVS6qEolu5Ucrmtz2khvDXjaH/PeBZMEr5T177YrwOWowQgMM42Z2yVyEMw2WrLfMJ0RhQHnWv1+PGRdAXZL7s4l6aHPL+jaAmDzi+wPKegIu7FUmeEo/f+pINW2VhAk2afHj3rWEcUYkUrJ6/LvfPplZywNIwcaZNBWD7BYcKky03w4SFTV+0N1xmPMc1pvEKTjmhU2LDudznnBxqe81Hl/4qE74tVbcP5c3XCM9PBEo/qxZF2x/ADlV8gmKAGm7XvVjybEwNMeSsIIYVTW5x62Pw7OJmdqLRxh1iXazqD+ypvbIgVFckskw9LO2EU5+chcP8K8y3D6qJBPTQVMAHBMlHvfIL3jnu7gKdeTbDdQbqzFsvCsgz2m8PVkJO7Dg6Tb1/jsQyLvOmupg+Ac42mPRK8wuk4MIZjoLMZTMwqT6PdJkPkS3snjE4xQroCUsHIf2fji3JgmJHOuERHWcwRyPXvw8u3ZhL/XftxGepCnL8MifsTZZgMnvxKIxmuyh07HVV4UlDiD8vFHLnmuYsAQBkDNG9D9D/CKnnoREhXYt1UkE8LbemxMA4iso1rN0ZrLUZsrHFkX/gO2NuTkAcVBbprRKQ=
    on:
      branch: master
      tags: true